"""doppler_sheet.py - printable Doppler tuning playbook sheet.

A single-page PDF table of corrected RX/TX frequencies across a pass, for manual
tuning without a computer in the loop. For a linear transponder the sheet states
which leg is held fixed and that the other is round-trip corrected.
"""

import datetime as _dt

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages

PAGE_W_IN = 8.5
PAGE_H_IN = 11.0
C_TITLE = "#0b3d91"
C_RULE = "#0b3d91"
C_ALT = "#eef2fa"


def _utc(unix, fmt="%Y-%m-%d %H:%M:%S UTC"):
    return _dt.datetime.fromtimestamp(
        unix, _dt.timezone.utc).strftime(fmt)


def generate_doppler_sheet(path, sat, rows, hold="downlink"):
    if not rows:
        raise ValueError("no playbook rows")
    t0 = rows[0]["t"]
    mode = rows[0]["mode"]
    with PdfPages(path) as pdf:
        fig = plt.figure(figsize=(PAGE_W_IN, PAGE_H_IN))
        fig.subplots_adjust(left=0.08, right=0.92, top=0.86, bottom=0.06)
        ax = fig.add_subplot(111)
        ax.axis("off")
        # header
        fig.text(0.08, 0.955, "%s \u2014 Doppler Tuning Playbook" % sat.name,
                 fontsize=16, fontweight="bold", color=C_TITLE)
        sub = ("Pass starting %s   \u2014   mode: %s" % (_utc(t0), mode))
        fig.text(0.08, 0.93, sub, fontsize=9.5, color="#333333")
        if "linear" in mode:
            note = ("Linear transponder, full duplex: the %s is held FIXED; "
                    "the other leg is round-trip corrected so you keep hearing "
                    "yourself. Park the fixed leg, follow the other." %
                    ("downlink" if hold == "downlink" else "uplink"))
        else:
            note = ("FM / independent channels: each leg is corrected on its "
                    "own (no shared passband). Tune RX and TX as listed.")
        import textwrap
        wrapped = "\n".join(textwrap.wrap(note, width=92))
        fig.text(0.08, 0.905, wrapped, fontsize=8.5, color="#555555",
                 va="top", linespacing=1.4)

        # table
        headers = ["Min", "Az", "El", "Range-rate (km/s)", "RX (MHz)",
                   "TX (MHz)"]
        cell = []
        for r in rows:
            cell.append([
                "%.1f" % ((r["t"] - t0) / 60.0),
                "%.0f\u00b0" % r.get("az", 0.0),
                "%.0f\u00b0" % r.get("el", 0.0),
                "%+.3f" % r["range_rate"],
                "%.4f" % (r["rx_hz"] / 1e6),
                ("%.4f" % (r["tx_hz"] / 1e6)) if r["tx_hz"] else "\u2014",
            ])
        tbl = ax.table(cellText=cell, colLabels=headers, loc="upper center",
                       cellLoc="center",
                       colWidths=[0.10, 0.10, 0.10, 0.26, 0.22, 0.22])
        tbl.auto_set_font_size(False)
        tbl.set_fontsize(9)
        tbl.scale(1, 1.4)
        # style header + zebra
        for (row, col), c in tbl.get_celld().items():
            c.set_edgecolor("#c8d2e6")
            if row == 0:
                c.set_facecolor(C_RULE)
                c.set_text_props(color="white", fontweight="bold")
                c.set_fontsize(8.5)        # header slightly smaller so it fits
            elif row % 2 == 0:
                c.set_facecolor(C_ALT)
        fig.text(0.08, 0.072,
                 "Generated by OrbitDeck. Frequencies assume the catalog "
                 "transponder edges; verify against the satellite's published "
                 "plan. Times UTC.", fontsize=7.5, color="#888888")
        try:
            from .. import __version__ as _ver
        except Exception:
            _ver = ""
        fig.text(0.5, 0.045,
                 "OrbitDeck%s \u2022 Paul Stoetzer, N8HM"
                 % (" v%s" % _ver if _ver else ""),
                 ha="center", va="bottom", fontsize=6.5, color="#9a9a9a")
        pdf.savefig(fig)
        plt.close(fig)
    return path
